name: pyplane
summary: PyPLANE
adopt-info: pyplane
description: |
  PyPLANE is an application written in Python for solving systems of Ordinary Differential Equations (ODEs). 
  It is intended as an open source replacement for Pplane and Dfield, two proprietary Java applications which are often used as teaching tools in academia.
base: core18
architectures:
  - build-on: [amd64]

# plugs:
#   gtk-3-themes:
#     interface: content
#     target: $SNAP/data-dir/themes
#     default-provider: gtk-common-themes:gtk-3-themes
#   icon-themes:
#     interface: content
#     target: $SNAP/data-dir/icons
#     default-provider: gtk-common-themes:icon-themes

parts:
  build-trigger:
    source: https://github.com/m-squared96/PyPLANE.git
    plugin: nil

  pyplane:
    source: https://github.com/m-squared96/PyPLANE.git
    source-branch: dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
    plugin: python
    python-version: "python3"
    python-packages: # These will be installed in the build VM using pip
      - numpy
      - sympy
      - scipy
      - matplotlib
      - pyqt5
    stage-packages: # These 
      - libfreetype6
      - libpng16-16
      - libgl1-mesa-glx
      - libegl1-mesa
      - libqt53danimation5
      - libqt53dcore5
      - libqt53dextras5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53dquick5
      - libqt53dquickscene2d5
      - libqt53drender5
      - libqt5gui5
      - libqt5texttospeech5
      - libqt5webengine5
      - libqt5webenginecore5
      - libqt5webview5
      - libxcomposite1
      - libasound2
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libcups2
      - libfontconfig1
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libodbc1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpq5
      - libpulse-mainloop-glib0
      - libpulse0
      - libspeechd2
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon-x11-0
      - libxkbcommon0
    
apps:
  pyplane:
    extensions:
      - kde-neon # Allows PyPLANE to use the kde-frameworks snap (inherit Qt theme and UI scale factor from operating system)
    adapter: full
    command: bin/run.py
    plugs: [desktop, unity7, x11, wayland, opengl, gsettings, desktop-legacy]

confinement: strict
